apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../components/external-secret
resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.15.0/cert-manager.yaml
  - prod_issuer.yaml
  - external-secret.yaml
