apiVersion: v1
kind: Namespace
metadata:
  name: data
  labels:
    name: data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: data
  labels:
    app: postgres-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-credentials
  namespace: data
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: postgres-secret
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: postgres
        property: POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: postgres
        property: POSTGRES_PASSWORD
    - secretKey: POSTGRES_DB
      remoteRef:
        key: postgres
        property: POSTGRES_DB
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
  namespace: data
  labels:
    app: postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
        - name: postgres-db
          image: postgres:18
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: postgres-secret
          ports:
            - name: postgres
              containerPort: 5432
          volumeMounts:
            - name: postgres-persistent-storage
              mountPath: /var/lib/postgresql
      volumes:
        - name: postgres-persistent-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  namespace: data
  labels:
    app: postgres-db
spec:
  selector:
    app: postgres-db
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
