apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-auth
  namespace: tailscale
spec:
  target:
    name: tailscale-auth
  data:
    - secretKey: TS_AUTHKEY
      remoteRef:
        key: tailscale-auth
        property: TS_AUTHKEY
