apiVersion: v1
kind: ServiceAccount
metadata:
  name: gha-deployer
  namespace: kube-system
---
apiVersion: v1
kind: Secret
metadata:
  name: gha-deployer-token
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: gha-deployer
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gha-deployer
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["batch"]
    resources: ["cronjobs", "jobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["services", "configmaps", "persistentvolumeclaims", "persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "create", "patch", "update"]
  - apiGroups: ["external-secrets.io"]
    resources: ["externalsecrets", "clusterexternalsecrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["postgresql.cnpg.io"]
    resources: ["clusters"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gha-deployer
subjects:
  - kind: ServiceAccount
    name: gha-deployer
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: gha-deployer
  apiGroup: rbac.authorization.k8s.io
